#!/usr/bin/env python3
"""
normalize_pe.py -- pin the volatile bytes in a Windows PE so that two builds
of the same source produce the same file hash (reproducible / stable-hash
builds), without needing a code-signing certificate.

What varies between otherwise-identical builds, and what this script pins:

  1. IMAGE_FILE_HEADER.TimeDateStamp (the "linker" timestamp).
  2. Every CodeView (IMAGE_DEBUG_TYPE_CODEVIEW) debug-directory entry's
     TimeDateStamp.
  3. The CodeView RSDS PDB GUID (regenerated by the linker on every build).
  4. The CodeView RSDS PDB path (an absolute path to the build machine).

The result is a pure function of (source + compiler + flags), independent of
build time, build machine, and PDB GUID. It preserves file size and is
idempotent (re-running changes nothing).

Usage:
    python normalize_pe.py <file> [<file> ...] [--stamp N] [--pdb NAME] [--quiet]

Defaults:
    --stamp  0x6554B000  (a fixed 2024-01-13-ish epoch, constant)
    --pdb    <basename>.pdb   (a stable relative name, no machine path)
"""
import argparse
import hashlib
import os
import struct
import sys

DEFAULT_STAMP = 0x6554B000  # fixed constant; any value works, must be constant
# Fixed 16-byte RSDS GUID (little-endian field layout as stored in the file).
# Constant so the hash is stable. Bytes of a made-up-but-stable GUID.
DEFAULT_GUID = bytes.fromhex("0de56e4152ab4a34a01b5d7f9c8e1234")

RSDS = b"RSDS"


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def e_lfanew(buf):
    # DOS header e_lfanew is at 0x3C
    return struct.unpack_from("<I", buf, 0x3C)[0]


def rva_to_offset(buf, sections, rva):
    """sections: list of (virtual_address, virtual_size, raw_ptr, raw_size)."""
    for vaddr, vsize, rptr, rsize in sections:
        # A RVA maps into a section if vaddr <= rva < vaddr + max(vsize, rsize)
        span = max(vsize, rsize)
        if vaddr <= rva < vaddr + span:
            return rptr + (rva - vaddr)
    return None


def read_sections(buf, pe_off):
    """Return (num_sections, section_table_off, list of section tuples)."""
    # COFF header: machine(2) num_sections(2) ts(4) symrva(4) nsyms(4)
    #   opt_size(2) chars(2)  -> opt header starts at pe_off+24
    num_sections = struct.unpack_from("<H", buf, pe_off + 6)[0]
    opt_size = struct.unpack_from("<H", buf, pe_off + 20)[0]
    opt_off = pe_off + 24
    magic = struct.unpack_from("<H", buf, opt_off)[0]
    is_pe32plus = (magic == 0x20B)
    # IMAGE_OPTIONAL_HEADER64: NumberOfRvaAndSizes @ +0x6C, DataDirectory[] @ +0x70.
    # IMAGE_OPTIONAL_HEADER32:  NumberOfRvaAndSizes @ +0x64, DataDirectory[] @ +0x68.
    if is_pe32plus:
        num_dd = struct.unpack_from("<I", buf, opt_off + 108)[0]
        dd_off = opt_off + 112
    else:
        num_dd = struct.unpack_from("<I", buf, opt_off + 100)[0]
        dd_off = opt_off + 104
    section_off = opt_off + opt_size
    sections = []
    for i in range(num_sections):
        o = section_off + i * 40
        # Name(8) vsize(4) vaddr(4) rawsize(4) rawptr(4) ...
        vsize = struct.unpack_from("<I", buf, o + 8)[0]
        vaddr = struct.unpack_from("<I", buf, o + 12)[0]
        rsize = struct.unpack_from("<I", buf, o + 16)[0]
        rptr = struct.unpack_from("<I", buf, o + 20)[0]
        sections.append((vaddr, vsize, rptr, rsize))
    return num_sections, section_off, sections, dd_off, num_dd, is_pe32plus, opt_off


def normalize(path, stamp, pdb_name, quiet):
    with open(path, "rb") as f:
        buf = bytearray(f.read())

    if buf[:2] != b"MZ":
        print(f"  {path}: skip (not MZ)", file=sys.stderr)
        return False

    before = hashlib.sha256(bytes(buf)).hexdigest()
    pe_off = e_lfanew(buf)
    if buf[pe_off:pe_off + 4] != b"PE\x00\x00":
        print(f"  {path}: skip (no PE sig)", file=sys.stderr)
        return False

    changed = False

    # 1. PE TimeDateStamp at pe_off+8
    old_ts = struct.unpack_from("<I", buf, pe_off + 8)[0]
    if old_ts != stamp:
        struct.pack_into("<I", buf, pe_off + 8, stamp)
        changed = True

    (num_sections, section_off, sections, dd_off, num_dd, is_pe32plus, opt_off) = (
        read_sections(buf, pe_off))

    # 2. Debug directory = data directory index 6
    if num_dd > 6:
        dd_rva, dd_size = struct.unpack_from("<II", buf, dd_off + 6 * 8)
        if dd_rva:
            dd_off_file = rva_to_offset(buf, sections, dd_rva)
            if dd_off_file is not None:
                n_entries = dd_size // 28
                for i in range(n_entries):
                    e = dd_off_file + i * 28
                    chars, ts, maj, mino, typ, dsize, drva, res = struct.unpack_from(
                        "<IIHHIIII", buf, e)
                    if typ != 2:  # IMAGE_DEBUG_TYPE_CODEVIEW
                        continue
                    # 2a. pin the debug entry timestamp
                    if ts != stamp:
                        struct.pack_into("<I", buf, e + 4, stamp)
                        changed = True
                    # 2b. pin the RSDS GUID + PDB path
                    data_off = rva_to_offset(buf, sections, drva)
                    if data_off is None or dsize < 24:
                        continue
                    magic = bytes(buf[data_off:data_off + 4])
                    if magic != RSDS:
                        continue
                    guid_off = data_off + 4
                    age_off = guid_off + 16
                    path_off = age_off + 4
                    # pin GUID
                    buf[guid_off:guid_off + 16] = DEFAULT_GUID
                    changed = True
                    # find original path extent: from path_off to first NUL (utf-16)
                    p = path_off
                    path_end = p
                    while path_end + 1 < len(buf) and buf[path_end:path_end + 2] != b"\x00\x00":
                        path_end += 2
                    # region to overwrite = [path_off, path_end)
                    region = path_end - path_off
                    newp = pdb_name.encode("utf-16-le")
                    if len(newp) > region:
                        # can't fit; truncate to fit (keeps size stable)
                        newp = newp[:region - 2]
                    if bytes(buf[path_off:path_end]) != newp:
                        buf[path_off:path_off + len(newp)] = newp
                        # pad remainder of region with NUL
                        if path_off + len(newp) < path_end:
                            buf[path_off + len(newp):path_end] = b"\x00" * (path_end - (path_off + len(newp)))
                        changed = True

    if changed:
        with open(path, "wb") as f:
            f.write(bytes(buf))
        after = hashlib.sha256(bytes(buf)).hexdigest()
        if not quiet:
            print(f"  {os.path.basename(path)}: normalized "
                  f"(ts {old_ts:08X}->{stamp:08X})")
            print(f"    {before[:16]}... -> {after[:16]}...")
    else:
        if not quiet:
            print(f"  {os.path.basename(path)}: already normalized")
    return changed


def main():
    ap = argparse.ArgumentParser(description="Pin volatile PE bytes for stable hashes.")
    ap.add_argument("files", nargs="+")
    ap.add_argument("--stamp", type=lambda x: int(x, 0), default=DEFAULT_STAMP,
                    help="fixed PE timestamp (dec or 0xhex). default %(default)s")
    ap.add_argument("--pdb", default=None,
                    help="fixed PDB path to embed (default: <basename>.pdb)")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    for path in args.files:
        if not os.path.exists(path):
            if not args.quiet:
                print(f"  {os.path.basename(path)}: skip (not present)")
            continue
        pdb = args.pdb
        if pdb is None:
            pdb = os.path.splitext(os.path.basename(path))[0] + ".pdb"
        try:
            normalize(path, args.stamp, pdb, args.quiet)
        except Exception as ex:
            print(f"  {os.path.basename(path)}: ERROR {ex}", file=sys.stderr)
            sys.exit(2)


if __name__ == "__main__":
    main()
